{
 "title": "Node Dashboard",
 "description": "Dashboard for the IOTA node sofware",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "message_type",
    "query": {
     "query": "label_values(iota_gossip_node_message_count, type)"
    }
   },
   {
    "name": "peers",
    "query": {
     "query": "label_values(iota_gossip_peers_message_count, alias)"
    }
   },
   {
    "name": "peer_message_type",
    "query": {
     "query": "label_values(iota_gossip_peers_message_count, type)"
    }
   },
   {
    "name": "peer_request_type",
    "query": {
     "query": "label_values(iota_gossip_peers_request_count, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_node_app_info" }
   ]
  },
  {
   "title": "Node version",
   "type": "stat",
   "description": "Node Version",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_node_app_info" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the node",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"iota-node\"}"
    }
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "description": "The sync stat of the Node",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iota_node_milestones{type=\"latest\"} - on () iota_node_milestones{type=\"confirmed\"}"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "description": "Health status of the node",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_node_health" }
   ]
  },
  {
   "title": "MPS",
   "type": "stat",
   "description": "Messages and referenced messages per second",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_messages_per_second", "legendFormat": "MPS" },
    {
     "expr": "iota_node_referenced_messages_per_second",
     "legendFormat": "RMPS"
    }
   ]
  },
  {
   "title": "Ratio RMPS to MPS",
   "type": "stat",
   "description": "Ratio of referenced messages in relation to new messages of the last confirmed milestone.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_referenced_rate" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "CPU usage",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"iota-node\"}[30s]) * 100"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "RAM usage",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(go_memstats_heap_inuse_bytes{job=\"iota-node\"} + (go_memstats_heap_idle_bytes{job=\"iota-node\"} - go_memstats_heap_released_bytes{job=\"iota-node\"}) + go_memstats_mspan_inuse_bytes{job=\"iota-node\"} + go_memstats_mcache_inuse_bytes{job=\"iota-node\"} + go_memstats_stack_sys_bytes{job=\"iota-node\"})"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size of the ledger database",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_database_size_bytes" }
   ]
  },
  {
   "title": "Neighbors",
   "type": "stat",
   "description": "Neighbors count",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iota_gossip_peers_connected_count)"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "description": "Current MPS",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_messages_per_second" }
   ]
  },
  {
   "type": "stat",
   "description": "MPS in the last 10 minutes",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_messages_per_second" }
   ]
  },
  {
   "type": "stat",
   "description": "MPS in the last day",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "iota_node_messages_per_second" }
   ]
  },
  {
   "title": "Milestones",
   "type": "stat",
   "description": "Milestone stats",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_node_milestones{type=\"confirmed\"}",
     "legendFormat": "Confirmed"
    },
    {
     "expr": "iota_node_milestones{type=\"latest\"}",
     "legendFormat": "Latest"
    },
    {
     "expr": "iota_node_milestones{type=\"latest\"} - on() iota_node_milestones{type=\"confirmed\"}",
     "legendFormat": "Milestones behind"
    },
    {
     "expr": "iota_node_milestones{type=\"latest\"} - on() iota_node_milestones{type=\"pruning\"}",
     "legendFormat": "Milestones in DB"
    },
    {
     "expr": "iota_node_milestones{type=\"pruning\"}",
     "legendFormat": "Pruning index"
    },
    {
     "expr": "iota_node_milestones{type=\"snapshot\"}",
     "legendFormat": "Snapshot index"
    }
   ]
  },
  {
   "title": "Is compacting/pruning",
   "type": "stat",
   "description": "Pruning and compaction status",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_database_pruning_running", "legendFormat": "Pruning" },
    {
     "expr": "iota_database_compaction_running",
     "legendFormat": "Compacting"
    }
   ]
  },
  {
   "type": "stat",
   "description": "MPS in the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_messages_per_second" }
   ]
  },
  {
   "title": "Gossip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Per Second",
     "type": "graph",
     "description": "Messages per second per type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(iota_gossip_node_message_count{type=~\"$message_type\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "graph",
     "description": "Requests Per second per type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_gossip_node_request_count[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Heartbeats Per Second",
     "type": "stat",
     "description": "Heartbeats per second",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(iota_gossip_node_heartbeat_count[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Sent Heartbeats Per Peer",
     "type": "piechart",
     "description": "Distribution of sent heartbeats per peer",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_gossip_peers_heartbeat_count{type=\"sent\"}",
       "legendFormat": "{{alias}} - Sent"
      }
     ]
    },
    {
     "title": "Received Heartbeats Per Peer",
     "type": "piechart",
     "description": "Distribution of received heartbeats per peer",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_gossip_peers_heartbeat_count{type=\"received\"}",
       "legendFormat": "{{alias}} - Received"
      }
     ]
    },
    {
     "title": "Dropped Packages",
     "type": "stat",
     "description": "Sum of dropped packages",
     "gridPos": { "h": 8, "w": 4, "x": 15, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_gossip_node_dropped_count" }
     ]
    },
    {
     "title": "Dropped Packages Per Peer",
     "type": "piechart",
     "description": "Distribution of dropped packages per peer",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_gossip_peers_dropped_count",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Messages Per Second Per Peer",
     "type": "graph",
     "description": "MPS per peer per type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_message_count{type=~\"$peer_message_type\", alias=~\"$peers\"}[1m])",
       "legendFormat": "{{alias}} - {{type}}"
      }
     ]
    },
    {
     "title": "Requests Per Second Per Peer",
     "type": "graph",
     "description": "Requests per second per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_request_count{type=~\"$peer_request_type\", alias=~\"$peers\"}[1m])",
       "legendFormat": "{{alias}} - {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caches Size",
     "type": "graph",
     "description": "Cache sizes per type",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "iota_caches_size", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Database size",
     "type": "graph",
     "description": "Size of the Ledger database",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "iota_database_size_bytes" }
     ]
    },
    {
     "title": "Compaction/Pruning Counts",
     "type": "stat",
     "description": "Compaction and Pruning Counts",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_database_pruning_count", "legendFormat": "Pruning" },
      { "expr": "iota_database_compaction_count", "legendFormat": "Compaction" }
     ]
    }
   ]
  },
  {
   "title": "Migrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receipts Metrics",
     "type": "stat",
     "description": "Stats for the migration receipts",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "iota_migrator_receipt_count", "legendFormat": "Receipt Count" },
      {
       "expr": "iota_migrator_receipt_entries_applied_count",
       "legendFormat": "Receipt Entries Applied Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tips",
     "type": "graph",
     "description": "Amount of tips per second",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(iota_node_tip_count[5m])", "legendFormat": " {{type}}" }
     ]
    },
    {
     "title": "Messages To Request",
     "type": "graph",
     "description": "Messages to request per second",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(iota_node_request_count[$__rate_interval])",
       "legendFormat": " {{type}}"
      }
     ]
    },
    {
     "title": "Http Request Errors",
     "type": "stat",
     "description": "Http request errors",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_restapi_http_request_error_count"
      }
     ]
    }
   ]
  }
 ]
}